[package]
name = "egui_curve_editor"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
egui = { version = "0.31.0", features = ["serde"] }
serde = { version = "1.0.218", features = ["serde_derive"] }
